import { fetchQuotes, type Quote } from "@/lib/api";

const STATUS_STYLES: Record<string, string> = {
  draft: "bg-gray-100 text-gray-700",
  pending_approval: "bg-yellow-100 text-yellow-800",
  approved: "bg-green-100 text-green-800",
  sent: "bg-green-100 text-green-800",
  rejected: "bg-red-100 text-red-700",
  expired: "bg-gray-100 text-gray-500",
};

function StatusBadge({ status }: { status: string }) {
  const style = STATUS_STYLES[status] ?? "bg-gray-100 text-gray-700";
  return (
    <span
      className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${style}`}
    >
      {status.replace("_", " ")}
    </span>
  );
}

function maskPhone(phone: string): string {
  const digits = phone.replace(/\D/g, "");
  if (digits.length < 4) return "XXXXXX";
  return `+XX XXXXXX${digits.slice(-4)}`;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default async function QuotesPage() {
  let quotes: Quote[] = [];
  let error: string | null = null;

  try {
    quotes = await fetchQuotes();
  } catch (e) {
    error = e instanceof Error ? e.message : "Unknown error";
  }

  return (
    <main className="mx-auto max-w-7xl px-4 py-8">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-gray-900">Quote History</h1>
        <p className="mt-1 text-sm text-gray-500">
          All quotes generated by AI conversations
        </p>
      </div>

      {error && (
        <div className="mb-4 rounded-md bg-red-50 p-4 text-sm text-red-800">
          Could not load quotes: {error}. Make sure the backend is running on{" "}
          <code className="font-mono">http://localhost:8000</code>.
        </div>
      )}

      {!error && quotes.length === 0 && (
        <div className="rounded-lg border border-dashed border-gray-300 p-12 text-center">
          <p className="text-gray-500">No quotes yet.</p>
          <p className="mt-1 text-sm text-gray-400">
            Start a conversation on WhatsApp to generate your first quote.
          </p>
        </div>
      )}

      {quotes.length > 0 && (
        <div className="overflow-x-auto rounded-lg border border-gray-200 bg-white shadow-sm">
          <table className="min-w-full divide-y divide-gray-200 text-sm">
            <thead className="bg-gray-50">
              <tr>
                {["Date", "Buyer", "Work", "Subtotal", "GST", "Total", "Status", "PDF"].map(
                  (h) => (
                    <th
                      key={h}
                      className="px-4 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500"
                    >
                      {h}
                    </th>
                  )
                )}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {quotes.map((q) => (
                <tr key={q.id} className="hover:bg-gray-50">
                  <td className="whitespace-nowrap px-4 py-3 text-gray-600">
                    {formatDate(q.created_at)}
                  </td>
                  <td className="px-4 py-3 font-mono text-gray-700">
                    {maskPhone(q.buyer_phone)}
                  </td>
                  <td className="px-4 py-3 capitalize text-gray-700">
                    {q.work_type.replace("_", " ")}
                  </td>
                  <td className="px-4 py-3 text-gray-700">Rs. {q.subtotal}</td>
                  <td className="px-4 py-3 text-gray-700">Rs. {q.gst_amount}</td>
                  <td className="px-4 py-3 font-semibold text-gray-900">
                    Rs. {q.total}
                  </td>
                  <td className="px-4 py-3">
                    <StatusBadge status={q.status} />
                  </td>
                  <td className="px-4 py-3">
                    {q.pdf_url ? (
                      <a
                        href={q.pdf_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 underline hover:text-blue-800"
                      >
                        View PDF
                      </a>
                    ) : (
                      <span className="text-gray-400">—</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </main>
  );
}
